---
- name: "aliases | add global bash_aliases file"
  template:
    src: etc/bash_aliases.j2
    dest: /etc/bash_aliases
    mode: 0644
    owner: root
    group: root
  tags:
    - aliases

- name: "aliases | source bash_aliases"
  lineinfile:
    path: /etc/bash.bashrc
    line: 'source /etc/bash_aliases'
    state: present
  tags:
    - aliases
